### ISSUE TITLE
Icons disappear due to caching issue?

### ISSUE THREAD

**Issue by oliverschloebe** [laxap/iconfont#2] opened 2015-12-22 12:10 UTC
Howdy,

there seems to be an issue with the icons randomly disappearing from the frontend... specifically the `.fa-xyz` class won't even be printed in the HTML markup.

So when normally the markup would be `<i class="fa fa-phone "></i>` it's changing to `<i class="phone"></i>` hence the icons disappear. The `fa fa-` part is generated through typoscript, but we're not coming up with a reason why it would omit the rendering of the `fa fa-` part randomly.

We couldn't really find a way to reproduce the issue, but it seems that the icons disappear after a user is logging in to the backend.

Has anyone noticed anything similar?

We're using TYPO3 6.2.x

**Comment by laxap** [comment] 2015-12-22 20:53
A bug was filed in forge by another user but I wasn't able to reproduce the issue during my first tests. 

Thank you for reporting it too. Finally I was able to reproduce it reliable! To me it seems to be a bug in TYPO3 core. But for more information and a quick fix see https://forge.typo3.org/issues/72272#note-2

**Comment by oliverschloebe** [comment] 2015-12-22 21:14
Hi laxap, thanks! Gonna try the quick fix and report (t)here.

**Comment by laxap** [comment] 2016-02-06 10:27
fixed in 0.7.4

**Closed as completed by laxap** 2016-02-06 10:27 UTC
